<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0">Pedidos de los usuarios</h1>
    <a href="<?= $this->url('sales', ['action' => 'add']) ?>"
        class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
            class="fas fa-download fa-sm text-white-50"></i> Actualizar estatus de pedidos</a>
</div>

<div class="row">
    <div class="col-12">
        <hr>
        <hr>
    </div>
    <div class="col-12 card card-body">
        <table id="table-content" class="table table-bordered text-center">
            <thead class="">
                <tr>
                    <th>No.</th>
                    <th>Nombre</th>
                    <th>Celular</th>
                    <th>Perfil</th>
                    <th>Producto</th>
                    <th>No. de canje único</th>
                    <th>Fecha</th>
                    <th>Estatus</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="overflow-auto">
                <?php foreach ($data as $row): ?>
                    <?php
                    $bg = "warning";
                    switch (((int) $row->tracking_status)):
                        case 1:
                            $bg = "info";
                            $estatus = "Procesando";
                            break;
                        case 3:
                            $bg = "success";
                            $estatus = "Entregado";
                            break;
                        default:
                            $estatus = "Enviado";
                    endswitch;

                    if ($row->type === 'ereward'):
                        $bg = "success";
                        $estatus = "Entregado";
                    endif;
                    ?>
                    <tr class="table-<?= $bg ?>">
                        <td>
                            <?php echo $row['id'] ?>
                        </td>
                        <td>
                            <?php echo $row['name'] ?>
                        </td>
                        <td>
                            <?php echo $row['username'] ?>
                        </td>
                        <td>
                            <?php echo $row['profile'] ?>
                        </td>
                        <td>
                            <?php echo $row['title'] ?>
                        </td>
                        <td>
                            <?php echo $row['adn'] ?>
                        </td>
                        <td>
                            <?php echo $row['created_at'] ?>
                        </td>
                        <td>
                            <?php echo $estatus ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('sales', ['action' => 'detail', 'id' => $row['order_id']]) ?>">
                                <i class="fa fa-eye" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>