<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Gana más con Newell')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink([
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon.ico'
                ])
                ->prependStylesheet($this->basePath('css/style.css?t=' . time()))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css')
                ->prependStylesheet('https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap4.min.css')
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                        >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/logo-h.png') ?>" alt="Movistar promociones">
                    </a>
                </div>
                
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                
            </footer>
        </div>
        <?=
                $this->inlineScript()
                ->prependFile($this->basePath('js/Script.js?t='.time()))
                ->prependFile('//cdn.jsdelivr.net/npm/sweetalert2@11')
                ->prependFile('https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap4.min.js')
                ->prependFile('https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js')
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
        ?>
    </body>
</html>
