<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php echo 'Tipo,Nombre,Total,Usados,Disponibles' ?>
<?php
echo chr(13);
foreach ($content as $row):
    echo
        utf8_decode($row['id']) . ',' .
        $row['code_type'] . ',' .
        $row['total'] . ',' .
        $row['used'] . ',' .
        $row['aval'] . ',' .
        chr(13);

endforeach;
header('Content-Description: File Transfer');
header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename=Reporte estatus de códigos.csv');
header('Content-Transfer-Encoding: binary');
header('Expires: 0');
header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Pragma: public');

?>