<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="content">
    <?php if ($error): ?>
        <div class="row">
            <div class="offset-md-2 col-8">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h3>Ocurrió un error al procesar el archivo</h3>
                    </div>
                    <div class="card-body">
                        <p>El archivo no se pudo leer, comprueba las siguientes razones:</p>
                        <ol>
                            <li>Que el archivo si tenga una extensión CSV</li>
                            <li>Que se encuentre debidamente llenado</li>
                            <li>Que sea un archivo CSV separado por comas</li>
                        </ol>
                        <p>Si tienes dudas, intena seguir los pasos citados en la página anterior</p>
                        <p>Si el problema persiste, por favor contacta al proveedor de servicio</p>
                    </div>
                    <div class="card-footer text-right">
                        <a class="btn btn-primary" href="<?= $this->url('application', ['action' => 'index']) ?>">
                            Aceptar
                        </a>
                    </div>
                </div>
            </div>
        </div>
    <?php else: ?>
        <?php if (count($fileContent) > 1): ?>
            <div class="row">
                <div class="col-12">
                    <div class="">
                        <h1 class="">Por favor confirma la información a procesar </h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-10 offset-md-1">
                    <table id="table-content" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Celular</th>
                                <th>Mes</th>
                                <th>Concepto</th>
                                <th>Puntos actuales</th>
                                <th>Puntos a cargar</th>
                                <th>Nuevo Balance</th>
                            </tr>
                        </thead>
                        <tbody class="overflow-auto">
                            <?php
                            $i = true;
                            foreach ($fileContent as $row):
                                if ($i):
                                    $i = false;
                                    continue;
                                endif ?>
                                <tr>
                                    <td>
                                        <?php echo $row[0] ?>
                                    </td>
                                    <td>
                                        <?php echo $row[1] ?>
                                    </td>
                                    <td>
                                        <?php echo $row[2] ?>
                                    </td>
                                    <td>
                                        <?php echo $row[3] ?>
                                    </td>
                                    <td>
                                        <?php echo isset($row[4]) ? $row[4] : 'N/A' ?>
                                    </td>
                                    <td>
                                        <?php echo isset($row[5]) ? $row[5] : 'N/A' ?>
                                    </td>
                                </tr>
                            <?php
                            endforeach ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="offset-md-8 col-3">
                    <br><input type="hidden" id="fid" value="<?= $fileId ?>">
                    <button class="btn btn-danger" id="cancel-button">NO confirmo</button> &nbsp;
                    <button class="btn btn-success" id="confirm-button">Confirmo y procesar</button>
                </div>
            </div>
        <?php else: ?>
            <div class="row">
                <div class="offset-md-2 col-8">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h3>Ocurrió un error al leer el archivo</h3>
                        </div>
                        <div class="card-body">
                            <p>El archivo no contiene información, comprueba las siguientes razones:</p>
                            <ol>
                                <li>Que el archivo si tenga una extensión CSV</li>
                                <li>Que se encuentre debidamente llenado</li>
                                <li>Que sea un archivo CSV separado por comas</li>
                            </ol>
                            <p>Si tienes dudas, intena seguir los pasos citados en la página anterior</p>
                            <p>Si el problema persiste, por favor contacta al proveedor de servicio</p>
                        </div>
                        <div class="card-footer text-right">
                            <a class="btn btn-primary" href="<?= $this->url('application', ['action' => 'index']) ?>">
                                Aceptar
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif ?>
    <?php
    endif ?>
</div>